library("igraph")
library("igraphdata")
#library("graph")
library("RBGL")
library("QuACN")
#library("plyr")
library("tidyverse")
library("magrittr")
library("tidygraph")
library("ggraph")

source("./R/Foos.R")